version: '3.8'
services:
  go-backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT:-9000}:9000"
      - "${DEBUG_PORT:-2345}:2345"
    environment:
      - KAFKA_BROKERS=${KAFKA_BROKERS:-kafka:9092}
      - REDIS_URL=${REDIS_URL:-redis:6379}
    networks:
      - digirobotics-network

networks:
  digirobotics-network:
    external: true