version: '3.8'

services:
  go-backend:
    build: 
      context: ./go-backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./go-backend:/app

  py-services:
    build:
      context: ./py-services
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    volumes:
      - ./py-services:/app