FROM golang:1.19

WORKDIR /app

# Initialize the module first
COPY go.mod go.sum ./
RUN go mod download

# Install air for hot reload
RUN go install github.com/cosmtrek/air@v1.40.4

# No need for VOLUME directive here
CMD ["air"]