apiVersion: apps/v1
kind: Deployment
metadata:
  name: robot-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: robot-backend
  template:
    metadata:
      labels:
        app: robot-backend
    spec:
      containers:
      - name: go-backend
        image: robot-backend:latest
        ports:
        - containerPort: 9000
        env:
        - name: KAFKA_BROKERS
          value: "kafka-service:9092"
        - name: REDIS_URL
          value: "redis-service:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: robot-backend-service
spec:
  selector:
    app: robot-backend
  ports:
  - port: 80
    targetPort: 9000
  type: LoadBalancer